steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'packages/chatterfix/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/chatterfix-backend:$COMMIT_SHA', './packages/chatterfix']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/chatterfix-backend:$COMMIT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'chatterfix-backend'
  - '--image=gcr.io/$PROJECT_ID/chatterfix-backend:$COMMIT_SHA'
  - '--region=us-central1'
  - '--platform=managed'
  - '--allow-unauthenticated'
  - '--set-secrets=GEMINI_API_KEY=GEMINI_API_KEY:latest,FIREBASE_KEY_JSON=FIREBASE_KEY_JSON:latest'

images:
- 'gcr.io/$PROJECT_ID/chatterfix-backend:$COMMIT_SHA'
