# Trigger rebuild: Streamlit syntax fix confirmation
import os
import streamlit as st

tool = st.sidebar.radio("Choose a tool to run:", ["Chat", "Review", "AutoPatch", "Summarize", "Logs", "📦 New App", "🧪 System Check"])

from tools.config import load_config
from tools.logger import log_markdown
from tools import openai_review
from plugins.autopatch import autopatch_run
from plugins.summarize import run as summarize_run
from tools import gemini_query

conf = load_config()

if tool == "Chat":
    st.subheader("💬 Chat Assistant")
    model = st.selectbox("Choose LLM", ["OpenAI (GPT-4)", "Gemini"])
    user_input = st.text_area("Enter your message:")
    if st.button("Send"):
        if model.startswith("OpenAI"):
            import openai
            client = openai.OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
            response = client.chat.completions.create(
                model=conf["openai"]["model"],
                messages=[
                    {"role": "system", "content": "You are a helpful assistant."},
                    {"role": "user", "content": user_input}
                ]
            )
            st.markdown(f"**GPT-4 Response:**\n\n{response.choices[0].message.content}")
        else:
            st.write("🧠 Sending to Gemini...")
            gemini_query.query_model(prompt=user_input)

elif tool == "Review":
    st.subheader("📄 GPT-4 Code Review")
    uploaded = st.file_uploader("Upload a Python file for review", type=["py"])
    if uploaded and st.button("Run Review"):
        tmp_path = "temp_review.py"
        with open(tmp_path, "w") as f:
            f.write(uploaded.read().decode())
        openai_review.review(target=tmp_path, supervised=False)
        with open("gpt_review.log", "r") as log:
            st.markdown("### 📝 GPT Review Output")
            st.code(log.read(), language="markdown")

elif tool == "AutoPatch":
    st.subheader("🛠 AutoPatchBoy (GPT-4)")
    uploaded = st.file_uploader("Upload a Python file to patch", type=["py"])
    if uploaded and st.button("Run AutoPatchBoy"):
        tmp_path = "temp_patch.py"
        with open(tmp_path, "w") as f:
            f.write(uploaded.read().decode())
        class Args:
            """Placeholder docstring for Args."""
            target=tmp_path
            supervised=False
        autopatch_run(Args())

elif tool == "Summarize":
    st.subheader("🧾 File Summarizer")
    uploaded = st.file_uploader("Upload a text or code file", type=["py", "txt", "md"])
    if uploaded and st.button("Summarize"):
        tmp_path = "temp_summary.txt"
        with open(tmp_path, "w") as f:
            f.write(uploaded.read().decode())
        class Args: target=tmp_path
        summarize_run(Args())

elif tool == "Logs":
    st.subheader("📚 Review Logs (Latest Patches)")
    log_dir = "logs/patches"
    if os.path.exists(log_dir):
        files = sorted(os.listdir(log_dir))[-5:]
        for file in reversed(files):
            st.markdown(f"### 📄 `{file}`")
            with open(os.path.join(log_dir, file), "r") as f:
                st.markdown(f.read())
    else:
        st.info("No patch logs found yet.")

elif tool == "📦 New App":
    st.subheader("📦 Create New App Module")
    app_name = st.text_input("Enter new app name:")
    if st.button("Create App"):
        base_path = f"apps/{app_name}"
        os.makedirs(base_path, exist_ok=True)
        with open(f"{base_path}/main.py", "w") as f:
            f.write(f"# {app_name} entry point\n\nprint('Hello from {app_name}')\n")
        with open(f"{base_path}/README.md", "w") as f:
            f.write(f"# {app_name}\n\nGenerated by GringoOps.")
        st.success(f"✅ Created new app: {app_name}")

elif tool == "🧪 System Check":
    st.subheader("🧪 Environment & Dependency Check")

    import platform
    import streamlit as stlib

    st.markdown("### 🔑 API Key Status")
    st.write("OPENAI_API_KEY:", "✅ Found" if os.getenv("OPENAI_API_KEY") else "❌ Missing")
    st.write("GOOGLE_API_KEY:", "✅ Found" if os.getenv("GOOGLE_API_KEY") else "❌ Missing")
    st.write("HUGGINGFACE_API_KEY:", "✅ Found" if os.getenv("HUGGINGFACE_API_KEY") else "⚠️ Optional")

    st.markdown("### 🐍 Python Environment")
    st.write("Python version:", platform.python_version())
    st.write("Streamlit version:", stlib.__version__)

    st.markdown("### 📁 Directory Checks")
    st.write("Logs folder:", "✅ Found" if os.path.exists("logs/patches") else "❌ Missing")
    st.write("Plugins folder:", "✅ Found" if os.path.exists("plugins") else "❌ Missing")