apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fredfix-agent
spec:
  template:
    spec:
      containers:
        - image: gcr.io/YOUR_PROJECT_ID/fredfix-agent:latest
          ports:
            - containerPort: 8080
          env:
            - name: OPENAI_API_KEY
              value: "YOUR_OPENAI_API_KEY"
