name: Deploy to Google Cloud Run

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check GCP_SA_KEY_BASE64 Secret
        env:
          GCP_SA_KEY_BASE64: ${{ secrets.GCP_SA_KEY_BASE64 }}
        run: |
          if [ -z "$GCP_SA_KEY_BASE64" ]; then
            echo "GCP_SA_KEY_BASE64 is NOT set."
            exit 1
          else
            echo "✅ GCP_SA_KEY_BASE64 is set."
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          for f in requirements.txt Gringo_Ops/ChatterFix/requirements.txt GringoOpsHub/requirements.txt; do
            if [ -f "$f" ]; then pip install -r "$f"; fi
          done

      - name: Write GCP credentials to file
        run: echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 -d > /tmp/key.json

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_BASE64 }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: chatterfix-ui

      - name: Test GCP Authentication
        run: gcloud projects list || { echo '❌ GCP auth failed'; exit 1; }

      - name: Deploy to Cloud Run
        run: |
          echo "🚀 Deploying ChatterFix to Cloud Run..."
          gcloud run deploy chatterfix-api \
            --source . \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --project chatterfix-ui

      - name: Confirm Deployment
        run: |
          echo "✅ Checking deployed app..."
          curl --fail --silent https://chatterfix-api-uc.a.run.app || exit 1