name: Deploy to Google Cloud Run

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decode base64 GCP key
        id: decode-key
        run: |
          echo "json<<EOF" >> $GITHUB_OUTPUT
          echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 -d >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ steps.decode-key.outputs.json }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: chatterfix-ui

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy chatterfix-api \
            --source . \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --project chatterfix-ui

      - name: Confirm Deployment
        run: |
          echo "✅ Checking deployed app..."
          curl --fail --silent https://chatterfix-api-uc.a.run.app || exit 1