name: Deploy to Google Cloud Run

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check GCP_SA_KEY_BASE64 Secret
        env:
          GCP_SA_KEY_BASE64: ${{secrets.GCP_SA_KEY_BASE64}}
        run: |
          if [ -z "$GCP_SA_KEY_BASE64" ]; then
            echo "GCP_SA_KEY_BASE64 is NOT set."
            exit 1
          else
            echo "GCP_SA_KEY_BASE64 is set."
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f Gringo_Ops/ChatterFix/requirements.txt ]; then pip install -r Gringo_Ops/ChatterFix/requirements.txt; fi
          if [ -f GringoOpsHub/requirements.txt ]; then pip install -r GringoOpsHub/requirements.txt; fi

      - name: Decode base64 GCP key
        id: decode-key
        run: |
          echo "json<<EOF" >> $GITHUB_OUTPUT
          echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 -d >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ steps.decode-key.outputs.json }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: chatterfix-ui

      - name: Test GCP Authentication
        run: |
          gcloud projects list || { echo 'GCP authentication failed or insufficient permissions.'; exit 1; }

      - name: Deploy to Cloud Run
        run: |
          if [ ! -f Dockerfile ]; then echo "ERROR: Dockerfile missing in root"; exit 1; fi
          if [ ! -f pyproject.toml ]; then echo "ERROR: pyproject.toml missing in root"; exit 1; fi
          gcloud run deploy chatterfix-api \
            --source . \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --project chatterfix-ui

      - name: Confirm Deployment
        run: |
          echo "✅ Checking deployed app..."
          curl --fail --silent https://chatterfix-api-uc.a.run.app || exit 1