name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.yaml'
      - '**/*.json'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: chatterfix-ui

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy chatterfix-api \
          --source . \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --project chatterfix-ui

    - name: Confirm Deployment
      run: |
        echo "✅ Checking service status..."
        curl --fail --silent --show-error https://chatterfix-api-uc.a.run.app || exit 1