name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Decode and validate GCP key
      run: |
        echo "$GCP_SA_KEY_BASE64" | base64 -d > /tmp/key.json
        jq -e '.client_email and .private_key and .project_id' /tmp/key.json > /dev/null || exit 1
      env:
        GCP_SA_KEY_BASE64: ${{ secrets.GCP_SA_KEY_BASE64 }}

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_file: /tmp/key.json

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: chatterfix-ui

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy chatterfix-api \
          --source . \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --project chatterfix-ui

    - name: Confirm Deployment
      run: |
        echo "✅ Checking service status..."
        curl --fail --silent --show-error https://chatterfix-api-uc.a.run.app || exit 1