name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'packages/chatterfix/**'
      - '.github/workflows/deploy-backend.yaml'

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: 'Submit build to Cloud Build'
        uses: 'google-github-actions/cloud-build@v1'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          config: 'cloudbuild.yaml'
