name: Test GCP Authentication

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  test-auth:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: 'Authenticate to Google Cloud'
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Verify Authentication'
        run: |
          echo "Successfully authenticated with the service account:"
          gcloud auth list --filter=status:ACTIVE --format='value(account)'

      - name: 'Verify Project ID and Permissions'
        run: |
          echo "Verifying project ID and permissions..."
          gcloud projects describe ${{ secrets.GCP_PROJECT_ID }} --format="value(name)"
          echo "Project ID is valid and the service account has permissions to access it."
