# .streamlit/config.toml
[server]
headless = true
port = 8501
enableCORS = false

[theme]
primaryColor = "#F63366"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[client]
toolbarMode = "minimal"

[logger]
level = "info"
